/home/hs01/ezyang/ghc-gcampax/inplace/lib/bin/haddock -B/home/hs01/ezyang/ghc-gcampax/inplace/lib -l/home/hs01/ezyang/ghc-gcampax/inplace/lib --odir=libraries/compact/dist-install/doc/html/compact --no-tmp-comp-dir --dump-interface=libraries/compact/dist-install/doc/html/compact/compact.haddock --html --hoogle --title=compact-1.0.0.0: In memory storage of deeply evaluated data structure --prologue=libraries/compact/dist-install/haddock-prologue.txt --read-interface=../base-4.8.1.0,../base-4.8.1.0/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../bytestring-0.10.6.0,../bytestring-0.10.6.0/src/%{MODULE/./-}.html#%{NAME},libraries/bytestring/dist-install/doc/html/bytestring/bytestring.haddock --read-interface=../deepseq-1.4.1.1,../deepseq-1.4.1.1/src/%{MODULE/./-}.html#%{NAME},libraries/deepseq/dist-install/doc/html/deepseq/deepseq.haddock --read-interface=../ghc-prim-0.4.0.0,../ghc-prim-0.4.0.0/src/%{MODULE/./-}.html#%{NAME},libraries/ghc-prim/dist-install/doc/html/ghc-prim/ghc-prim.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-Werror --optghc=-Wall --optghc=-H64m --optghc=-O0 --optghc=-this-package-key --optghc=compa_DojhKtForqB0Ecv3alk8AX --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/compact/. --optghc=-ilibraries/compact/dist-install/build --optghc=-ilibraries/compact/dist-install/build/autogen --optghc=-Ilibraries/compact/dist-install/build --optghc=-Ilibraries/compact/dist-install/build/autogen --optghc=-Ilibraries/compact/. --optghc=-optP-include --optghc=-optPlibraries/compact/dist-install/build/autogen/cabal_macros.h --optghc=-package-key --optghc=base_GDytRqRVSUX7zckgKqJjgw --optghc=-package-key --optghc=rts --optghc=-package-key --optghc=bytes_6elQVSg5cWdFrvRnfxTUrH --optghc=-package-key --optghc=deeps_LbCWUlehDDeLxurARKDH5o --optghc=-package-key --optghc=ghcpr_8TmvWUcS1U1IKHT0levwg3 --optghc=-Wall --optghc=-XHaskell2010 --optghc=-O2 --optghc=-O --optghc=-dcore-lint --optghc=-fno-warn-deprecated-flags --optghc=-fno-warn-tabs --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/compact/dist-install/build --optghc=-hidir --optghc=libraries/compact/dist-install/build --optghc=-stubdir --optghc=libraries/compact/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/compact/./Data/Compact.hs libraries/compact/./Data/Compact/Incremental.hs libraries/compact/./Data/Compact/Monad.hs libraries/compact/./Data/Compact/Imp.hs +RTS -tlibraries/compact/dist-install/doc/html/compact/compact.haddock.t --machine-readable 
 [("bytes allocated", "454807568")
 ,("num_GCs", "83")
 ,("average_bytes_used", "12272478")
 ,("max_bytes_used", "31110552")
 ,("num_byte_usage_samples", "5")
 ,("peak_megabytes_allocated", "72")
 ,("init_cpu_seconds", "0.000")
 ,("init_wall_seconds", "0.000")
 ,("mutator_cpu_seconds", "0.334")
 ,("mutator_wall_seconds", "0.363")
 ,("GC_cpu_seconds", "0.289")
 ,("GC_wall_seconds", "0.289")
 ]
